# Generated by Django 3.2.8 on 2022-01-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_auto_20220131_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_pinjam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
