# Generated by Django 3.2.8 on 2022-01-31 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0003_alter_pinjam_tgl_pinjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='judul',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main2.buku'),
            preserve_default=False,
        ),
    ]
