# Generated by Django 3.2.8 on 2022-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0004_pinjam_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_kembali',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_pinjam',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
